### ISSUE TITLE
TODO:LIST

### ISSUE THREAD

**Issue by OL1Y1ER** [OL1Y1ER/Neural-Network-exp#6]
- [x] Multiple Activation Functions
- [ ] Test "GiveRandomNumbers()"
- [ ] Write code for "Training Algorithm"
- [x] Write code for "Saving Neural Network"
- [ ] Write Documentation
- [ ] TEST
- [ ] TEST
- [ ] TEST
- [ ] TEST

**Comment by OL1Y1ER** [comment]
Also, I have to check if it works on different platforms!
🙀
